const workspaces = [
  ['NaveeFit','Fitness','1','₹','Active'],
  ['VR LuminousCraft','Digital Agency','1','₹','Active'],
  ['VR Rahul','Marketing Agency','1','₹','Active'],
  ['VDVDFV','Photography','1','₹','Active'],
  ['Studio One','Photography','4','₹','Active'],
];
const nav = [['⌂','Home'],['▦','Workspaces'],['♟','Users'],['₹','Subscriptions'],['◇','Modules'],['▤','Industry Templates'],['♟','Roles & Permissions'],['◉','Customers'],['♡','Interested Customers'],['◷','Audit Logs'],['♢','Notifications'],['⌁','Automations'],['✦','Lumi AI']];
export default function Admin(){return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark">L</div><div><div className="brandName">LuMekH™</div><small>PLATFORM</small></div></div><div className="nav">{nav.map(([i,n],idx)=><a key={n} className={idx===0?'active':''} href={idx===1?'#workspaces':'#'}><span className="icon">{i}</span>{n}</a>)}</div></aside><main className="main"><header className="topbar"><div className="crumb">LuMekH™ <b>/ Platform overview</b></div><div className="topRight"><input className="search" placeholder="⌕  Search..."/><div className="avatar"><span>LM</span>Lavan</div></div></header><section className="hero"><div className="eyebrow">LUMEKH ADMIN</div><h1>Platform Overview</h1><p>Control workspaces, users, product modules and the LuMekH platform from one command center.</p></section><section className="cards"><div className="card metric" style={{background:'#e0f0fc'}}><div className="label">Workspaces</div><div className="value">5</div><div className="trend">registered workspaces</div></div><div className="card metric" style={{background:'#eadff6'}}><div className="label">Users</div><div className="value">12</div><div className="trend">platform accounts</div></div><div className="card metric" style={{background:'#e1f2e7'}}><div className="label">Customers</div><div className="value">38</div><div className="trend">registered customers</div></div><div className="card metric" style={{background:'#f8edc9'}}><div className="label">Active workspaces</div><div className="value">5</div><div className="trend">currently active</div></div></section><section className="sectionGrid" id="workspaces"><div className="panel"><div className="panelHead"><h2>Workspace registry</h2><p>Manage every business workspace registered in LuMekH.</p></div><div className="tableWrap"><table className="table"><thead><tr><th>NAME</th><th>BUSINESS</th><th>MEMBERS</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{workspaces.map(w=><tr key={w[0]}><td><b>{w[0]}</b></td><td>{w[1]}</td><td>{w[2]}</td><td><span className="pill">● {w[4]}</span></td><td><div className="actions"><button className="smallBtn">Open</button><button className="smallBtn">Suspend</button></div></td></tr>)}</tbody></table></div></div><div className="panel"><div className="panelHead"><h2>System status</h2><p>LuMekH platform foundation</p></div><div className="rows">{[['Authentication','Active'],['Workspace engine','Active'],['Database engine','Healthy'],['Automation engine','Healthy'],['Suspended workspaces','0']].map(([a,b])=><div className="row" key={a}><span>{a}</span><b>{b}</b></div>)}</div></div></section></main></div>}
